language: c
install: true
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libxml2-dev
script:
  - rm -rf build
  - mkdir build
  - cd build
  - cmake .. -DCMAKE_BUILD_TYPE=Debug
  - make
  - ./example/xlfsample
  - cd ..

